#!/bin/bash
pyfile=$PYFILE
if [ -z "$pyfile" ]; then
    echo "Missing environment variable PYFILE"
    exit 1
fi

output_file="${pyfile}c"
python3 -m compileall "$pyfile"
echo "Compiling $pyfile ..."
mv "__pycache__/$output_file" "$output_file"
